### ISSUE TITLE
Not working as of 1.4.0.3

### ISSUE THREAD

**Issue by qabRieL99** [trigger-death/TerrariaLocalizationPacker#1] opened 2020-05-22 20:59 UTC
Unpack works fine but repacking doesn't.

**Comment by trigger-segfault** [comment] 2020-06-07 08:02
Found the cause, and confirmed the solution. The resource names changed up a bit with the latest release (except for localization files).  The name changes were throwing off the `EmbeddedAssemblyResolver` needed for the libraries stored within Terraria.

Now Terraria searches for its embedded assemblies by checking if a resource name ends with the requested `assembly.Name + ".dll"`, so Localization Packer will need to do the same.

Hotfix should be submitted sometime tomorrow. I still need to ensure backwards compatibility with 1.3.5, and handle one other minor issue.  👍

**Comment by trigger-segfault** [comment] 2020-06-09 04:09
This is now fixed in commit b9248f93a26f60f79e8ba04f4d9d7ed3498c70ff, and released as version [1.0.0.3](https://github.com/trigger-segfault/TerrariaLocalizationPacker/releases/tag/1.0.0.3).

**Closed as completed** 2020-06-09 04:09 UTC
Labels: bug
